"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from telnetlib import LOGOUT
import dj_database_url
import django_on_heroku
from django.conf.locale.pt_BR import formats as br_formats

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zv+_43jkyp$rp^h7hz!(5hrc1+n@(1tw9gptqs&h5*xkgpr52y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'apps.custos',
    'apps.tax',
    'apps.empresa',
    'apps.produtos',
    'apps.contratos',
    'apps.contabilidade',
    'apps.orcamento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""
DATABASES = {
    'default' : dj_database_url.config()
}
"""


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Bahia'

USE_I18N = True

USE_TZ = True

DATE_FORMAT = 'd/m/Y'
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR=True

#Formato personalizados
br_formats.DATE_FORMAT = 'd/m/Y'
br_formats.DECIMAL_SEPARATOR = ','
br_formats.USE_THOUSAND_SEPARATOR=True
br_formats.THOUSAND_SEPARATOR = '.'
br_formats.NUMBER_GROUPING = 3



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

django_on_heroku.settings(locals())


JAZZMIN_SETTINGS = {
    "site_title": "Análise de Custos",
    "site_header": "Análise de Custos",
    "site_brand": "Análise de Custos",
    #"site_logo": "logo.png",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Bem vindo",
    "copyright": "SIEMP Tech",
    #"search_model": "auth.User",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "contabilidade.fechamento": "fas fa-lock",
        "contabilidade.planodecontas": "fas fa-clipboard",
        "Contratos.contratos":"fas fa-file-signature",
        "custos.grupocustos":"fas fa-layer-group",
        "custos.itemcustos":"fas fa-stream",
        "custos.itemprodutos":"fas fa-boxes",
        "custos.precoitemcustos":"fas fa-money-bill-wave-alt",
        "custos.provisaocustos":"fas fa-chart-line",
        "custos.subgrupocustos":"fas fa-clone",
        "empresa.empresa":"fas fa-building",
        "orcamento.orcamento":"fas fa-drafting-compass",
        "Produtos.grupoproduto":"fas fa-layer-group",
        "Produtos.produtos":"fas fas fa-box",
        "TAX.aliquotas":"fas fa-balance-scale",
        "TAX.categoriatributo":"fas fa-file-alt",
        "TAX.tributo":"fas fa-hand-holding-usd",
        "authtoken.tokenproxy":"fas fa-user-lock",

    },
}
