# Generated by Django 4.0.1 on 2022-03-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Grupo dos Produtos')),
            ],
            options={
                'verbose_name': 'Grupo de Produtos',
                'verbose_name_plural': 'Grupos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do Produto')),
                ('grupo_produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruposprodutos', to='produtos.grupoproduto', verbose_name='Grupo dos Produtos')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
