# Generated by Django 4.0.1 on 2022-03-15 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano')),
                ('jan', models.BooleanField(default=False, verbose_name='Janeiro')),
                ('fev', models.BooleanField(default=False, verbose_name='Fevereiro')),
                ('mar', models.BooleanField(default=False, verbose_name='Março')),
                ('abr', models.BooleanField(default=False, verbose_name='Abril')),
                ('mai', models.BooleanField(default=False, verbose_name='Maio')),
                ('jun', models.BooleanField(default=False, verbose_name='Junho')),
                ('jul', models.BooleanField(default=False, verbose_name='Julho')),
                ('ago', models.BooleanField(default=False, verbose_name='Agosto')),
                ('set', models.BooleanField(default=False, verbose_name='Setembro')),
                ('out', models.BooleanField(default=False, verbose_name='Outubro')),
                ('nov', models.BooleanField(default=False, verbose_name='Novembro')),
                ('dez', models.BooleanField(default=False, verbose_name='Dezembro')),
            ],
            options={
                'verbose_name': 'Fechamento',
                'verbose_name_plural': 'Fechamento',
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código do plano de contas do ERP', max_length=14, verbose_name='Código')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('reduzido', models.CharField(blank=True, max_length=3, null=True, verbose_name='Reduzido')),
                ('analitica', models.BooleanField(default=False, verbose_name='Analítica')),
                ('patrimonial', models.BooleanField(default=False, verbose_name='Patrimonial')),
                ('natureza', models.CharField(choices=[('C', 'Credora'), ('D', 'Devedora')], max_length=1, verbose_name='Natureza')),
                ('seq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seq')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_contabilidade', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
            },
        ),
    ]
