# Generated by Django 4.0.1 on 2022-03-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria dos Tributos',
                'verbose_name_plural': 'Categorias dos Tributos',
            },
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do Tributo')),
                ('CategoriaTributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriatributos', to='tax.categoriatributo', verbose_name='Categoria dos Tributos')),
            ],
            options={
                'verbose_name': 'Tributo',
                'verbose_name_plural': 'Tributos',
            },
        ),
        migrations.CreateModel(
            name='Aliquotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota', models.DecimalField(decimal_places=2, help_text='Informar o percentual sem o símbolo %', max_digits=10, verbose_name='Alíquota')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='empresa.empresa', verbose_name='Empresa')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='tax.tributo', verbose_name='Tributo')),
            ],
            options={
                'verbose_name': 'Alíquota',
                'verbose_name_plural': 'Alíquotas',
            },
        ),
    ]
