# Generated by Django 4.0.1 on 2022-03-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_crs', models.CharField(help_text='Informe o código do ERP referente ao contrato', max_length=100, verbose_name='Cod Centro Resultado')),
                ('cod_grupo', models.CharField(help_text='Informe o código de agrupamento', max_length=100, verbose_name='Cod Grupo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome do Contrato')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_contratos', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
