# Generated by Django 4.0.1 on 2022-03-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('contratos', '0001_initial'),
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Informe a data de competência', verbose_name='Data da Competência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('versao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Versão')),
                ('movimento', models.CharField(choices=[('1', '1'), ('-1', '-1')], max_length=2, verbose_name='Movimento')),
                ('cod_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_contabil', to='contabilidade.planodecontas', verbose_name='Conta Contábil do Orçamento')),
                ('cod_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_contratos', to='contratos.contratos', verbose_name='Contrato do Orçamento')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_empresas', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
    ]
